config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/', to: 'user#index', as:'root'

  #Show list
  get '/sneaker', to: 'sneaker#index', as: 'sneakers'

  #Sell a pair
  get '/sneaker/new', to: 'sneaker#new', as: 'new_sneaker'
  post '/sneaker', to: 'sneaker#sell', as: 'sell_sneaker'

  #Show a pair 
  get '/sneaker/:id', to: 'sneaker#show', as: 'sneaker'
  
  #Show user profile
  get '/user/show/:id', to: 'user#show', as: 'user'
  
  #Edit profile
  get '/user/edit/:id', to: 'user#edit', as: 'edit_profile'
  patch '/user/edit', to: 'user#update', as: "update_profile"
  
  #Show listing
  get '/user/show/:id/listing', to: 'listing#index', as:'listings'

  #Remove sneakers from listing
  delete '/sneaker/delete', to: 'listing#destroy', as: "remove_from_listings"

  
  #Show wishlist
  get '/wishlist', to: 'wishlist#index', as: 'wishlists'
  
  #Add sneakers to wishlist
  post '/wishlist', to: 'wishlist#add', as: 'add_to_wishlist'
  
  #Remove sneaker from wishlist
  delete '/sneaker/:id', to: 'wishlist#destroy', as:'remove_from_wishlist'
  
  #Administration
  get '/admin', to: 'admin#index', as: 'administration'
  
  #Block user
  get '/admin/edit/:id', to: 'admin#edit', as: 'edit_user'
  patch '/admin/edit', to: 'admin#update', as: "update_user"

  #Unblock user
  # get '/admin/edit/:id', to: 'admin#adit', as: 'clear_user'
  # patch '/admin/edit', to: 'admin#unblock', as: 'unblock_user'



  #Messages within conversation
  resources :conversations do
    resources :messages
  end
  

end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  belongs_to :sneaker
end

app/controllers/listing_controller.rb
class ListingController < ApplicationController
    def index
        @user = User.find(params[:id])
    end

    # Verifying a pair of sneakers and querying to whether to delete sneaker from wishlist
    def destroy
        user = current_user
        item_id = Sneaker.find(params[:id])
        Wishlist.where(sneaker_id: params[:id]).destroy_all
        item_id.destroy
        redirect_to user_path(user)
    end


end

app/helpers/listing_helper.rb
module ListingHelper
end

app/views/listing/index.html.erb
<h2>My Listing</h2>

<div class="container">
    <div id="listing-wrapper">
        <% @user.sneakers.each do |sneaker| %>
        <div id="listing-card">
            <div class="listing-items">
            <%= image_tag sneaker.picture if sneaker.picture.attached?%>
            <p><%="#{sneaker.brand}"%><p>
            <p><%="#{sneaker.model}"%><p>
            <p><%="size: #{sneaker.size}"%><p>
            <p><%= number_to_currency sneaker.price %><p>
            <%=link_to "Remove", remove_from_listings_path(:id => sneaker), method: "delete" %>
            </div>
        </div>
    <%end%>
    </div>
</div>
    
</div>