config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/', to: 'user#index', as:'root'

  #Show list
  get '/sneaker', to: 'sneaker#index', as: 'sneakers'

  #Sell a pair
  get '/sneaker/new', to: 'sneaker#new', as: 'new_sneaker'
  post '/sneaker', to: 'sneaker#sell', as: 'sell_sneaker'

  #Show a pair 
  get '/sneaker/:id', to: 'sneaker#show', as: 'sneaker'
  
  #Show user profile
  get '/user/show/:id', to: 'user#show', as: 'user'
  
  #Edit profile
  get '/user/edit/:id', to: 'user#edit', as: 'edit_profile'
  patch '/user/edit', to: 'user#update', as: "update_profile"
  
  #Show listing
  get '/user/show/:id/listing', to: 'listing#index', as:'listings'

  #Remove sneakers from listing
  delete '/sneaker/delete', to: 'listing#destroy', as: "remove_from_listings"

  
  #Show wishlist
  get '/wishlist', to: 'wishlist#index', as: 'wishlists'
  
  #Add sneakers to wishlist
  post '/wishlist', to: 'wishlist#add', as: 'add_to_wishlist'
  
  #Remove sneaker from wishlist
  delete '/sneaker/:id', to: 'wishlist#destroy', as:'remove_from_wishlist'
  
  #Administration
  get '/admin', to: 'admin#index', as: 'administration'
  
  #Block user
  get '/admin/edit/:id', to: 'admin#edit', as: 'edit_user'
  patch '/admin/edit', to: 'admin#update', as: "update_user"

  #Unblock user
  # get '/admin/edit/:id', to: 'admin#adit', as: 'clear_user'
  # patch '/admin/edit', to: 'admin#unblock', as: 'unblock_user'



  #Messages within conversation
  resources :conversations do
    resources :messages
  end
  

end

app/models/sneaker.rb
class Sneaker < ApplicationRecord
    belongs_to :user
    has_one_attached :picture

    #Implementing "fuzzy" allows user to easily search a sneaker without typing in the exact words
    def self.search(search)
        if search
            result = self.where("LOWER(brand) LIKE ?", "%#{search.downcase}%")
            if result.length > 0
                return result
            else
                result = self.where("LOWER(model) LIKE ?", "%#{search.downcase}%")
                return result
            end
        else
            Sneaker.all
        end
    end
end

app/controllers/sneaker_controller.rb
class SneakerController < ApplicationController
    def index
        @sneaker = Sneaker.search(params[:search])
    end

    # Create new sneaker
    def new
        @sneaker = Sneaker.new
    end

    # Validates each attribute before saving it to the database 
    def sell
        user = current_user
        @sneaker = user.sneakers.create(
            brand: params[:sneaker][:brand],
            model: params[:sneaker][:model],
            price: params[:sneaker][:price],
            size: params[:sneaker][:size],
        )
        @sneaker.picture.attach(params[:sneaker][:picture])

        if @sneaker.valid? && @sneaker.save
            redirect_to sneakers_path()
        else 
            render :new
        end
    end

    def show
        @sneaker = Sneaker.find(params[:id])
        @user = User.find(@sneaker.user_id)

    end

private 
    def sneaker_params
        params.require(:sneaker).permit(:brand,:model,:sneaker_id,:search)
    end

end

app/helpers/sneaker_helper.rb
module SneakerHelper
end

app/views/sneaker/index.html.erb
<h2>Sneaker list</h2>
   <div class="container">
      <div class="row">
        <% @sneaker.each do |sneaker| %>
         <div class="card">
            <p><%= link_to (image_tag sneaker.picture, class:"thumbnail-img" if sneaker.picture.attached?), sneaker_path(sneaker.id)%></p>
            <p class="p-3 mb-2 bg-dark text-white"><%="#{sneaker.brand}"%></p>
            <p class="p-3 mb-2 bg-light text-dark"><%="#{sneaker.model}"%></p>
            <p class="p-3 mb-2 bg-dark text-white"><%= number_to_currency sneaker.price%> <%= "(size: #{sneaker.size})"%></p>
         </div>
        <% end %>
      </div>
   </div>

app/views/sneaker/new.html.erb
<h2>Sell a pair of kicks</h2>

<div class="background">
    <%=image_tag("Sell-img.jpg", id:"login-page")%>
    <div class="sale-form">
    <% if user_signed_in? %>
        <%= form_with model: @sneaker, url: sell_sneaker_path do |form|%>
            <%= form.label :brand %>
            <%= form.select :brand, ["Air Jordan","Nike","Adidas","Balenciaga","Puma","New Balance","Reebok", "Vans", "Converse"] %>
            <br />
            
            <%= form.label :model %>
            <%= form.text_field :model %>
            <br />
            
            <%= form.label :price %>
            <%= form.number_field :price, min:0, max:20000 %>
            <br />

            <%= form.label :size %>
            <%= form.number_field :size, min: 1, max: 20 %>
            <br />
            
            <%= form.label :picture%>
            <%= form.file_field :picture, accept: "image/png, image/gif, image/jpeg, image/jpg",required:true%>
            <br />
            <p id="submit"><%= form.submit "Submit", class: "btn btn-success"%></p>
            
        <% end %>
    <% end %>
    </div>
</div>

app/views/sneaker/show.html.erb
<div class="background">
    
       <%= image_tag (@sneaker.picture if @sneaker.picture.attached?), class:"image"%>
    <div class="content">
    <h1><%= "#{@sneaker.brand}"%></h1>
    <h4><%= "#{@sneaker.model}"%></h4>
    <h6><%= "#{@user.location}"%></h6>
        <p><%= "#{number_to_currency @sneaker.price}"%></p>
        <p><%= "Ad posted: #{@sneaker.updated_at.to_time.strftime('%B %e')}"%><p>
    <%if user_signed_in?%>   
        <%if current_user.admin || current_user.id == @sneaker.user_id%> 
            <p><%= "Seller: #{@user.first_name} #{@user.last_name}"%></p>
        <%else %>
            <p><%= "Seller: #{@user.first_name} #{@user.last_name}"%></p>
            <p><%=link_to "Add to wishlist", add_to_wishlist_path(:id => @sneaker.id), method: :post %></p>
            <p><%= link_to "Message seller for enquiries", conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: "post"%></p>
        <%end%>

    <%end%>
</div>