config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/', to: 'user#index', as:'root'

  #Show list
  get '/sneaker', to: 'sneaker#index', as: 'sneakers'

  #Sell a pair
  get '/sneaker/new', to: 'sneaker#new', as: 'new_sneaker'
  post '/sneaker', to: 'sneaker#sell', as: 'sell_sneaker'

  #Show a pair 
  get '/sneaker/:id', to: 'sneaker#show', as: 'sneaker'
  
  #Show user profile
  get '/user/show/:id', to: 'user#show', as: 'user'
  
  #Edit profile
  get '/user/edit/:id', to: 'user#edit', as: 'edit_profile'
  patch '/user/edit', to: 'user#update', as: "update_profile"
  
  #Show listing
  get '/user/show/:id/listing', to: 'listing#index', as:'listings'

  #Remove sneakers from listing
  delete '/sneaker/delete', to: 'listing#destroy', as: "remove_from_listings"

  
  #Show wishlist
  get '/wishlist', to: 'wishlist#index', as: 'wishlists'
  
  #Add sneakers to wishlist
  post '/wishlist', to: 'wishlist#add', as: 'add_to_wishlist'
  
  #Remove sneaker from wishlist
  delete '/sneaker/:id', to: 'wishlist#destroy', as:'remove_from_wishlist'
  
  #Administration
  get '/admin', to: 'admin#index', as: 'administration'
  
  #Block user
  get '/admin/edit/:id', to: 'admin#edit', as: 'edit_user'
  patch '/admin/edit', to: 'admin#update', as: "update_user"

  #Unblock user
  # get '/admin/edit/:id', to: 'admin#adit', as: 'clear_user'
  # patch '/admin/edit', to: 'admin#unblock', as: 'unblock_user'



  #Messages within conversation
  resources :conversations do
    resources :messages
  end
  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # User can have many wishlist items, listings, sneakers and conversations
  has_many :wishlists, dependent: :destroy
  has_many :sneakers, dependent: :destroy
  has_many :listings, dependent: :destroy
  has_many :conversations, :foreign_key => :sender_id, dependent: :destroy


end

app/controllers/user_controller.rb
class UserController < ApplicationController

    def index
    end

    def show
        @user = User.find(params[:id])
    end

    def edit
    end

    # Validates params and saves data once everything is verified
    def update
        profile = current_user
        profile.update(
            first_name: params[:first_name],
            last_name: params[:last_name],
            email: params[:email],
            location: params[:location],
            contact: params[:contact]
        )

        if profile.valid? && profile.save
            redirect_to root_path
        else
            render "edit"
        end
    end

end
 

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/edit.html.erb
<% if user_signed_in? %>
    <%= form_with model:@user, url:update_profile_path, method: :patch do|f| %>
        <div class="field">
            <%= f.label :first_name %><br />
            <%= f.text_field :first_name, value: current_user.first_name, autofocus: true, autocomplete: "" %>
        </div>

        <div class="field">
            <%= f.label :last_name %><br />
            <%= f.text_field :last_name, value: current_user.last_name, autofocus: true, autocomplete: "" %>
        </div>

        <div class="field">
            <%= f.label :email %><br />
            <%= f.email_field :email, value: current_user.email, autofocus: true, autocomplete: "email" %>
        </div>

        <div class="field">
            <%= f.label :location %><br />
            <%= f.text_field :location, value: current_user.location, autofocus: true, autocomplete: "location" %>
        </div>

        <div class="field">
            <%= f.label :contact %><br />
            <%= f.number_field :contact, value: current_user.contact, autofocus: true, autocomplete: "contact" %>
        </div>

        <div>
            <%= f.submit "Edit"%>
           
        </div>
    <%end%>
<%end%>

app/views/user/index.html.erb
<body>
    <div class="background">
        <%= image_tag("yeezy.jpg", id:"splash-img") %>
        <div class="box-1">
            <p>Buy and Sell Authentic Sneakers</p>
        </div>

        <div class="box-2">
            <p>Yeezy Boost 350 V2 'Oreo'</p>
        </div>
    </div>
</body>

app/views/user/show.html.erb
<div class="container">
    <div >
        <h2><%="#{@user.first_name}'s Profile"%></h2>
        <div>
        <%= image_tag "jordans.jpg", id:"image-2"%>
        </div>
    
    <div class="box-3">

    <p><%= "Name: #{@user.first_name} #{@user.last_name}"%></p>
    <p><%= "Email: #{@user.email}"%></p>
    <p><%= "Location: #{@user.location}"%></p>
    <p><%= "Contact: #{@user.contact}"%><p>
    <p><%= link_to "Edit profile", edit_profile_path, class:"link-to-text-color-2"%><p>
    </div>

<div>